name = "cbwigs-assets"
main = "external/src/worker.js"   # <-- fix the path
compatibility_date = "2025-09-06"

# Serve static files from the root dist/
assets = { directory = "dist", binding = "ASSETS" }